image: registry.gitlab.com/(group)/(repo)

services:
  - mysql:5.7
  - python:3.8.2

variables:
  MYSQL_DATABASE: test_name
  MYSQL_ROOT_PASSWORD: root_pass
  DB_HOST: mysql
  DB_USERNAME: root

stages:
  - test

Testing App:
  stage: test
  retry: 2
  only: [merge_requests]
  before_script:
  - echo "en_US UTF-8" > /etc/locale.gen
  - locale-gen en_US.UTF-8
  - export LANG=en_US.UTF-8
  - export LANGUAGE=en_US:en
  - export LC_ALL=en_US.UTF-8
  script:
    - ln -s /laradock/vendor vendor
    - composer install
    - python vendor/pveltrop/pyrunner/_cicd.py --project=${CI_PROJECT_TITLE} --url=${CI_PROJECT_URL}/-/commit/${CI_COMMIT_SHA} --branch=${CI_COMMIT_REF_NAME} --author=${GITLAB_USER_EMAIL} --pushbullet=${PUSHBULLET} --slack=${SLACK} --pbchannel=${PBCHANNEL}

  artifacts:
    when: on_failure
    name: "${CI_BUILD_STAGE}_${CI_BUILD_REF_NAME}_FAILED"
    paths:
      - "vendor/pveltrop/pyrunner/pyrunner"
      - "vendor/pveltrop/pyrunner/"
      - "pyrunner/pyrunner"
      - "pyrunner/"
    untracked: false
    expire_in: 1 day
